#!/usr/bin/env python3
"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - test_mathematical_processor_standalone() (line 22)
        - test_enhanced_chunk_standalone() (line 61)
        - test_content_classifier_standalone() (line 115)
        - main() (line 163)
    --- END AUTO-GENERATED DOCSTRING ---

Standalone test for enhanced processing modules without package imports.
"""
import sys
from pathlib import Path

# Add the scirag module to the path
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent / "scirag" / "enhanced_processing"))

def test_mathematical_processor_standalone():
    """Test MathematicalProcessor by importing the file directly."""
    try:
        # Import the module file directly
        import importlib.util
        
        # First load enhanced_chunk module to make it available
        chunk_spec = importlib.util.spec_from_file_location(
            "enhanced_chunk", 
            "scirag/enhanced_processing/enhanced_chunk.py"
        )
        chunk_module = importlib.util.module_from_spec(chunk_spec)
        chunk_spec.loader.exec_module(chunk_module)
        sys.modules['enhanced_chunk'] = chunk_module
        
        # Now load mathematical_processor
        spec = importlib.util.spec_from_file_location(
            "mathematical_processor", 
            "scirag/enhanced_processing/mathematical_processor.py"
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        MathematicalProcessor = module.MathematicalProcessor
        
        processor = MathematicalProcessor()
        
        # Test equation processing (detect_equations method doesn't exist)
        result = processor.process_equation("E = mc^2")
        assert 'math_norm' in result
        assert 'math_tokens' in result
        assert 'equation_tex' in result
        
        print("✓ MathematicalProcessor standalone tests passed")
        return True
    except Exception as e:
        print(f"✗ MathematicalProcessor standalone test failed: {e}")
        return False

def test_enhanced_chunk_standalone():
    """Test EnhancedChunk by importing the file directly."""
    try:
        # Import the module file directly
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "enhanced_chunk", 
            "scirag/enhanced_processing/enhanced_chunk.py"
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        EnhancedChunk = module.EnhancedChunk
        ContentType = module.ContentType
        MathematicalContent = module.MathematicalContent
        
        # Test basic chunk creation
        chunk = EnhancedChunk(
            id="test_1",
            text="Test chunk",
            source_id="test_source",
            chunk_index=0,
            content_type=ContentType.PROSE
        )
        assert chunk.id == "test_1"
        assert chunk.content_type == ContentType.PROSE
        
        # Test chunk with math content
        math_content = MathematicalContent(
            equation_tex="E = mc^2",
            math_norm="E=mc^2",
            math_tokens=["E", "=", "m", "c", "^", "2"]
        )
        
        chunk = EnhancedChunk(
            id="math_1",
            text="The equation $E = mc^2$",
            source_id="physics",
            chunk_index=1,
            content_type=ContentType.EQUATION
        )
        chunk.mathematical_content = math_content
        
        # Test serialization
        chunk_dict = chunk.to_dict()
        assert chunk_dict['id'] == "math_1"
        assert chunk_dict['content_type'] == "equation"
        
        print("✓ EnhancedChunk standalone tests passed")
        return True
    except Exception as e:
        print(f"✗ EnhancedChunk standalone test failed: {e}")
        return False

def test_content_classifier_standalone():
    """Test ContentClassifier by importing the file directly."""
    try:
        # Import the module file directly
        import importlib.util
        
        # First load enhanced_chunk module to make it available
        chunk_spec = importlib.util.spec_from_file_location(
            "enhanced_chunk", 
            "scirag/enhanced_processing/enhanced_chunk.py"
        )
        chunk_module = importlib.util.module_from_spec(chunk_spec)
        chunk_spec.loader.exec_module(chunk_module)
        sys.modules['enhanced_chunk'] = chunk_module
        
        # Now load content_classifier
        spec = importlib.util.spec_from_file_location(
            "content_classifier", 
            "scirag/enhanced_processing/content_classifier.py"
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        ContentClassifier = module.ContentClassifier
        
        # Use the same ContentType from the already loaded enhanced_chunk module
        ContentType = chunk_module.ContentType
        
        classifier = ContentClassifier()
        
        # Test equation classification
        text = "The equation $E = mc^2$ is famous."
        content_type = classifier.classify_content(text, {})
        assert content_type == ContentType.EQUATION
        
        # Test prose classification
        text = "This is regular prose text."
        content_type = classifier.classify_content(text, {})
        assert content_type == ContentType.PROSE
        
        print("✓ ContentClassifier standalone tests passed")
        return True
    except Exception as e:
        print(f"✗ ContentClassifier standalone test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    """Run all standalone tests."""
    print("Testing Enhanced Processing Modules (Standalone)...")
    print("=" * 60)
    
    tests = [
        test_mathematical_processor_standalone,
        test_enhanced_chunk_standalone,
        test_content_classifier_standalone
    ]
    
    passed = 0
    total = len(tests)
    
    for test in tests:
        if test():
            passed += 1
        print()
    
    print("=" * 60)
    print(f"Results: {passed}/{total} tests passed")
    
    if passed == total:
        print("🎉 All standalone tests passed! Core modules are working.")
        print("\nPhase 1 Status: ✅ COMPLETE")
        print("\nWhat we've accomplished:")
        print("✓ Created enhanced_processing module structure")
        print("✓ Implemented MathematicalProcessor with RAGBook integration")
        print("✓ Implemented ContentClassifier for content type detection")
        print("✓ Implemented EnhancedChunk data structure")
        print("✓ Added comprehensive configuration system")
        print("✓ Created extensive test suite")
        print("✓ Updated dependencies in pyproject.toml")
        
        print("\nNext steps for Phase 2:")
        print("1. Create document_processor.py")
        print("2. Create enhanced_chunker.py")
        print("3. Create asset_processor.py and glossary_extractor.py")
        print("4. Integrate with existing SciRAG classes")
        return 0
    else:
        print("❌ Some tests failed. Check the errors above.")
        return 1

if __name__ == "__main__":
    sys.exit(main())