"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - UserProxyAgent (line 14):
        - AssistantAgent (line 18):
    --- END AUTO-GENERATED DOCSTRING ---
"""
# Mock autogen module for notebook compatibility
import autogen_agentchat as autogen

# Mock classes for compatibility
class UserProxyAgent:
    def __init__(self, *args, **kwargs):
        pass

class AssistantAgent:
    def __init__(self, *args, **kwargs):
        pass
