"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - Settings (line 16):
        - AnswerSettings (line 21):
        - AgentSettings (line 26):
    --- END AUTO-GENERATED DOCSTRING ---
"""
# Mock paperqa module for notebook compatibility
from dataclasses import dataclass
from typing import Optional, Dict, Any

@dataclass
class Settings:
    """Mock Settings class"""
    pass

@dataclass
class AnswerSettings:
    """Mock AnswerSettings class"""
    pass

@dataclass
class AgentSettings:
    """Mock AgentSettings class"""
    pass
