"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - get_directory_index(*args, **kwargs) (line 10)
    --- END AUTO-GENERATED DOCSTRING ---
"""
# Mock paperqa.agents.search module for notebook compatibility
def get_directory_index(*args, **kwargs):
    """Mock get_directory_index function"""
    return {"mock": "index"}
